name: product_data_checkpoint
config_version: 1.0
template_name:
module_name: great_expectations.checkpoint
class_name: Checkpoint
run_name_template: 'my-run-name-template'
expectation_suite_name:
batch_request: {}
action_list:
  - name: store_validation_result
    action:
      class_name: StoreValidationResultAction
  - name: store_evaluation_params
    action:
      class_name: StoreEvaluationParametersAction
  - name: datahub_action
    action: 
      module_name: datahub.integrations.great_expectations.action
      class_name: DataHubValidationAction
      server_url: http://35.120.124.334:8080
      env: PROD
      platform_alias: databricks
      platform_instance_map: {
        my_datasource : 581376643122154.metastore-id.main
      }
  - name: update_data_docs
    action:
      class_name: UpdateDataDocsAction
      site_names: []
evaluation_parameters: {}
runtime_configuration: {}
validations:
  - batch_request:
      datasource_name: my_datasource
      data_connector_name: default_inferred_data_connector_name
      data_asset_name: product_schema.product_data
      data_connector_query:
        index: -1
    expectation_suite_name: product_data_suite
profilers: []
ge_cloud_id:
expectation_suite_ge_cloud_id:
